language: elixir
elixir:
  - 1.10.1
otp_release:
  - 22.0
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix compile
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
# cache:
#   directories:
#     - _build
#     - deps
